### PR TITLE
Update ScriptHandler.ts

### PR DESCRIPTION
**Pull request by kstan79**
fix async resolve user via `#(....)` doesnt work

### CODE REVIEW

**Comment by ralphhanna** [comment]
No this does not work. a return must be in the script itself not provided.

See example below, does not work
```ts
           var item=this;
            var data=this.data;
            var input=this.input;
            var output=this.output;
            var appDelegate=this.token.execution.appDelegate;
            var appServices=this.token.execution.servicesProvider;
            var appUtils=appDelegate.appUtils;
            
                  return item.data.includeDepartment = true;
item.data.departments = ["IT"];
console.log('data',item.data);

```

**Comment by kstan79** [comment]
Seems the use case or script effect here. 

However, at user task set assignee won't consider the compatibility with script task. Shall we separate it?

**Comment by ralphhanna** [comment]
This works fine for me:
```ts
#return(appServices.getSampleUser('someParameterHere'));
```
You can place this in the user assignee:
image

**Comment by kstan79** [comment]
This method for prove of concept is ok, but really not recommend for production. Hope you can consider safety and reliability.

**Comment by ralphhanna** [comment]
What would you suggest instead?
Thanks

**Comment by kstan79** [comment]
After some try I suggest don't allow access JS run time via bpmn.use restricted pattern as #190

**Comment by ralphhanna** [comment]
please elaborate

**Comment by kstan79** [comment]
I think we go back #190 to discuss

**Pull request merged**
