### PR TITLE
chore: delete useless files

### LINKED ISSUE #149: Remove .js and .js.map file
I'm confused by the style of this repo, can you remove those generated file? They belong to /dist , and should be git ignored, so I don't have to commit and clone them.

Also, Can you publish the docs to a github page? If the doc is generated from source, maybe this should be done in github action, and not commit to the master branch.

### PR DESCRIPTION
**Pull request by linonetwo**
```pwsh
Get-ChildItem -Path src -Recurse -Filter *.d.ts | Remove-Item -Force
Get-ChildItem -Path src -Recurse -Filter *.js | Remove-Item -Force
Get-ChildItem -Path src -Recurse -Filter *.js.map | Remove-Item -Force
Get-ChildItem -Path src -Recurse -Filter *.ts.bak | Remove-Item -Force
```

fixes #149

### CODE REVIEW

**Comment by ralphhanna** [comment]
Thanks, already had it fixed in new release.

**Comment by linonetwo** [comment]
So you have a fix haven't push to master?

**Comment by ralphhanna** [comment]
Please see branch "rel2.0.0"

**Comment by linonetwo** [comment]
Great, this will not only populate the bpmnServer organization, but also make this server project easier to understand!

**Comment by ralphhanna** [comment]
@linonetwo 
Can I please seek your assistance in testing the new release, still some issues with the build .
- We are now excluding the dist folder, so the installer needs to build
- Somehow webApp build does not work, does not recognize the package
Thanks

**Comment by linonetwo** [comment]
> the installer needs to build

what is the installer? I still don't know why it will run script on install.

I will look at https://github.com/bpmnServer/bpmn-web

**Comment by linonetwo** [comment]
A new PR in https://github.com/bpmnServer/bpmn-server/pull/153

**Comment by ralphhanna** [comment]
I didn't realize that we have to copy all those files every build, so I am suggesting a new folder structure:

image

**Comment by linonetwo** [comment]
What changed? You add a `npm` folder with what?

**Comment by linonetwo** [comment]
Let's discuss in an issue instead, I'm closing this to prevent this from being merged by mistake.

**Pull request closed without merging**
